@echo off
echo Stopping any running containers...
docker-compose down

echo Removing any old volumes to ensure clean state...
docker volume rm speak_ai_mongodb_data 2>nul

echo Double-checking user.py file is fixed...
powershell -Command "(Get-Content app\routes\user.py) -notmatch 'INFO:     Application startup complete.' | Set-Content app\routes\user.py"

echo Building and starting containers...
docker-compose up --build
